### ISSUE TITLE
Institution Tab Update

### ISSUE THREAD

**Issue by ercore** [EPSCoR/ercore8#1]
1. On the Participation Dates form, do not require an End Date
1. Move Participation dates to the EPSCoR Involvement tab
1. Rename **ERCore Overall Roles** to **Most Senior Project Role** and move to the EPSCoR Involvement tab

**Comment by tschet** [comment]
One of the reason's I've spent the last week re-doing fields is because of this problem. Drupal 7 had an optional end date on their date field. Drupal 8 has either a date field (no end) or date range. I chose date range for these fields, but it currently doesn't allow no end date, so I'm having to switch fields to use two date fields, one required start, and an optional end.

**Comment by tschet** [comment]
This change will be done in this weekend's update.

**Comment by ercore** [comment]
Please move **Programs** and **Components** to the EPSCoR Involvement Tab.

**Comment by tschet** [comment]
Should be corrected. I'm not sure how to change the status so I'm passing it back to you.

**Comment by ercore** [comment]
@tschet This is still showing up on my test site, which we pulled/installed on 5/16. Both Programs and Components is showing on the Institutions Tab and Programs is required.

I am moving this card back to Doing.

**Comment by ercore** [comment]
All requests are complete on this card. Closing this one.
